### ISSUE TITLE
ValueError found during loading your provided `.ipynb` notebook

### ISSUE THREAD

**Issue by pavaris-pm** [yunjiazhang/ReAcTable#2] opened 2024-01-23 02:03 UTC
@yunjiazhang I have tried this line according to your provided notebook to load `fasttext` model

# Problem 1
```python
import fasttext
ft = fasttext.load_model('cc.en.300.bin')
```

However, what i encountered during this line is that, do you have any idea of fixing it ? or how you get that `.bin` file from ?
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[85], line 2
      1 import fasttext
----> 2 ft = fasttext.load_model('cc.en.300.bin')

File /usr/local/lib/python3.10/dist-packages/fasttext/FastText.py:436, in load_model(path)
    434 def load_model(path):
    435     """Load a model given a filepath and return a model object."""
--> 436     return _FastText(model_path=path)

File /usr/local/lib/python3.10/dist-packages/fasttext/FastText.py:94, in _FastText.__init__(self, model_path, args)
     92 self.f = fasttext.fasttext()
     93 if model_path is not None:
---> 94     self.f.loadModel(model_path)
     95 self._words = None
     96 self._labels = None

ValueError: cc.en.300.bin cannot be opened for loading!
```

# Problem 2
Moreover, the model you have used for completion is `davinci-codex-002-msft`

but it always get this kind of error everytime just by run the code you provided
```
File /workspace/content/ReAcTable/ReAcTable/scripts/GptConnector.py:204, in GptCompletion(engine, prompt, suffix, max_tokens, temperature, top_p, n, stream, logprobs, stop, presence_penalty, frequency_penalty, best_of, debug, prompt_end)
    202 # when the quota is exceeded, this error can be raised as well
    203 if result is None:
--> 204     raise ValueError("This model's maximum context length is 8193 tokens.")
    205 elif result == "Rate limit":
    206     print("Rate limit detacted. Retrying after 20sec.")

ValueError: This model's maximum context length is 8193 tokens.
```

**Comment by jshtok** [comment] 2024-04-10 19:45
Hi @pavaris-pm 
I am also trying to use this repo. I believe the second problem you refer to is caused by the outdated OpenAI API in the code. You need to replace the `def GptCompletion()` function in the GPTConnector.py
I have replaced the 'else' case in the `def gpt(queue):`  function there by 
```
                messages = prompt2messages(prompt)
                # pprint.pprint(messages)
                # output = openai.ChatCompletion.create(
                print('one_openai_call')
                output = client.chat.completions.create(
                    model=engine,
                    temperature=temperature,
                    max_tokens = max_tokens,
                    messages = messages,
                    stream = stream
                )                
                our_output = {'choices':[{'text':''}]}
                our_output['choices'][0]['text'] = output.choices[0].message.content.strip('```')

```

**Comment by yunjiazhang** [comment] 2024-04-23 03:08
The issues were resolved with using with the new notebook provided. Sorry for the delay

**Closed as completed by yunjiazhang** 2024-04-23 03:08 UTC
